services:
  mongodb:
    image: mongo:7
    container_name: travelverse-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: travelverse
      MONGO_INITDB_ROOT_PASSWORD: travelverse
      MONGO_INITDB_DATABASE: travelverse
    ports:
      - "27017:27017"
    volumes:
      - travelverse-mongodb:/data/db

  redis:
    image: redis:7-alpine
    container_name: travelverse-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - travelverse-redis:/data

volumes:
  travelverse-mongodb:
  travelverse-redis:
